### ISSUE TITLE
안녕하세요, 당근마켓 글로벌 프로덕트팀 iOS개발자 David입니다.

### ISSUE THREAD

**Issue by GeekTree0101** [alstjd8826/carrot-market-clone-coding#1]
안녕하세요 @alstjd8826 님, 우선 당근마켓에 지원해주셔서감사합니다. 
사전에 저희 JD 기술스택이나 문화를 보셨을 텐데도 불구하고 React를 사용하여 과제를 제출하신 이유가 있으신지 궁금합니다. :]

**Comment by alstjd8826** [comment]
저는 지금 맥북을 가지고 있지 않습니다.
주문을 해놓은 상태이지만 기한이 8월 5일까지라고 알고 있었고, 저는 swift를 한번도 보지 못했기 때문에 '남은 기간동안
swift로 클론코딩을 할 수 있을까'에 대한 불안함이 생겼습니다.
그리고 개인적으로 어플리케이션을 만들어 보고 있는데 이또한 리액트를 사용해서 만들고 있기 때문에 리액트에 대한 자신감이 있었습니다.
그렇기 때문에 일단 지원이라도 해보자는 마음으로 우분투를 사용하고 있는 제가 현재 구현할 수 있는 방법인 리액트를 사용해서
구현해보았습니다.

2021년 7월 7일 (수) 오후 5:45, David Ha ***@***.***>님이 작성:
